sudo: required
services:
  - docker

before_install:
  - docker build -t eltonokawa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eltonokawa/react-test npm test

after_success:
  - docker build -t eltonokawa/udemy-multi-client ./client
  - docker build -t eltonokawa/udemy-multi-nginx ./nginx
  - docker build -t eltonokawa/udemy-multi-server ./server
  - docker build -t eltonokawa/udemy-multi-worker ./worker
  # login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push eltonokawa/udemy-multi-client
  - docker push eltonokawa/udemy-multi-nginx
  - docker push eltonokawa/udemy-multi-server
  - docker push eltonokawa/udemy-multi-worker